const translations = {
    'zh-CN': {
        'home': '首页',
        'about': '关于我们',
        'products': '产品展示',
        'contact': '联系我们',
        'slogan': '专业家居用品跨境B2B批发贸易',
        'slogan-desc': '为全球零售商提供高性价比的一站式采购解决方案',
        'contact-us': '联系我们',
        'feature1': '全球供应链',
        'feature1-desc': '深度整合中国优质制造资源与全球市场需求',
        'feature2': '产品丰富',
        'feature2-desc': '提供多样化的家居用品选择',
        'feature3': '专业服务',
        'feature3-desc': '为海外零售商提供专业的一站式服务',
        'address': '地址：FLAT/RM 122 1/F LIVEN HOUSE 61-63 KING YIP STREET KWUN TONG',
        'tel': '电话：852 6209 7685',
        'email': '邮箱：eversource739@gmail.com',
        'email-input':'电子邮箱：',
        'about-title': '关于我们',
        'about-desc': '我们是一家专注于家居用品跨境B2B批发贸易的企业，致力于为海外零售商、分销商及连锁超市提供高性价比的一站式采购解决方案。通过深度整合中国优质制造资源与全球市场需求，我们搭建起高效稳定的跨国供应链体系。',
        'about-subtitle':'专业家居用品供应商，为您提供优质产品',
        'mission': '我们的使命',
        'mission-desc': '为全球客户提供优质、创新、环保的家居用品，推动中国制造走向世界。',
        'vision': '我们的愿景',
        'vision-desc': '成为全球领先的家居用品B2B贸易平台，打造值得信赖的国际品牌。',
        'values': '核心价值观',
        'value1': '诚信经营，客户至上',
        'value2': '品质第一，创新驱动',
        'value3': '合作共赢，持续发展',
        'value4': '环保责任，绿色未来',
        'team-title': '专业团队',
        'team1': '采购团队',
        'team1-desc': '专业的采购团队，确保产品质量和价格优势',
        'team2': '国际业务',
        'team2-desc': '经验丰富的国际业务团队，提供专业服务',
        'team3': '物流团队',
        'team3-desc': '高效的物流团队，确保准时交付',
        'products-title': '产品展示',
        'all': '全部',
        'kitchen': '厨房用品',
        'bathroom': '卫浴用品',
        'decor': '家居装饰',
        'product1': '不锈钢厨具套装',
        'product1-desc': '高品质不锈钢材质，耐用实用',
        'product2': '浴室收纳套装',
        'product2-desc': '防水防潮，实用美观',
        'product3': '现代风格装饰品',
        'product3-desc': '简约时尚，提升家居品味',
        'product4': '陶瓷餐具套装',
        'product4-desc': '精美陶瓷，安全环保',
        'product5': '浴室清洁套装',
        'product5-desc': '专业清洁，方便实用',
        'product6': '创意摆件',
        'product6-desc': '独特设计，彰显个性',
        'inquiry': '询价',
        'contact-title': '联系我们',
        'contact-info': '联系信息',
        'send-message': '发送消息',
        'name': '姓名',
        'subject': '主题',
        'message': '消息',
        'send': '发送',
        'years': '年行业经验',
        'products-caterory': '种产品',
        'countries': '个国家',
        'latest-products': '最新产品',
        'view-more': '查看更多产品',
        'testimonials': '客户评价',
        'ready-to-start': '准备好开始合作了吗？',
        'contact-us-now': '立即联系我们，获取专业的产品咨询和报价',
        'contact-subtitle': '我们期待与您建立长期合作关系',
        'address-title': '公司地址',
        'tel-title': '联系电话',
        'email-title': '电子邮箱',
        'hours-title': '工作时间',
        'hours': '周一至周五: 9:00 - 18:00',
        'products-subtitle': '精选优质家居用品，满足您的各种需求',
        'more-products': '更多产品',
        'contact-for-more': '请联系我们获取完整产品目录',
        'testimonial1': '"EVER SOURCE 提供的产品质量非常好，价格也很合理。他们的服务非常专业，交货准时，是我们值得信赖的合作伙伴。"',
        'testimonial1-role': '美国零售商',
        'testimonial2': '"与 EVER SOURCE 合作多年，他们总能提供优质的产品和专业的服务。他们的团队反应迅速，解决问题及时，是我们重要的供应商。"',
        'testimonial2-role': '西班牙分销商',
        'testimonial3': '"EVER SOURCE 的产品种类丰富，质量稳定，价格有竞争力。他们的物流服务也很可靠，是我们长期合作的伙伴。"',
        'testimonial3-role': '澳大利亚进口商'
    },
    'zh-TW': {
        'home': '首頁',
        'about': '關於我們',
        'products': '產品展示',
        'contact': '聯繫我們',
        'slogan': '專業家居用品跨境B2B批發貿易',
        'slogan-desc': '為全球零售商提供高性價比的一站式採購解決方案',
        'contact-us': '聯繫我們',
        'feature1': '全球供應鏈',
        'feature1-desc': '深度整合中國優質製造資源與全球市場需求',
        'feature2': '產品豐富',
        'feature2-desc': '提供多樣化的家居用品選擇',
        'feature3': '專業服務',
        'feature3-desc': '為海外零售商提供專業的一站式服務',
        'address': '地址：FLAT/RM 122 1/F LIVEN HOUSE 61-63 KING YIP STREET KWUN TONG',
        'tel': '電話：852 6209 7685',
        'email': '郵箱：eversource739@gmail.com',
        'email-input':'電子郵箱：',
        'about-title': '關於我們',
        'about-desc': '我們是一家專注於家居用品跨境B2B批發貿易的企業，致力於為海外零售商、分銷商及連鎖超市提供高性價比的一站式採購解決方案。通過深度整合中國優質製造資源與全球市場需求，我們搭建起高效穩定的跨國供應鏈體系。',
        'about-subtitle':'專業家居用品供應商，為您提供優質產品',
        'mission': '我們的使命',
        'mission-desc': '為全球客戶提供優質、創新、環保的家居用品，推動中國製造走向世界。',
        'vision': '我們的願景',
        'vision-desc': '成為全球領先的家居用品B2B貿易平台，打造值得信賴的國際品牌。',
        'values': '核心價值觀',
        'value1': '誠信經營，客戶至上',
        'value2': '品質第一，創新驅動',
        'value3': '合作共贏，持續發展',
        'value4': '環保責任，綠色未來',
        'team-title': '專業團隊',
        'team1': '採購團隊',
        'team1-desc': '專業的採購團隊，確保產品質量和價格優勢',
        'team2': '國際業務',
        'team2-desc': '經驗豐富的國際業務團隊，提供專業服務',
        'team3': '物流團隊',
        'team3-desc': '高效的物流團隊，確保準時交付',
        'products-title': '產品展示',
        'all': '全部',
        'kitchen': '廚房用品',
        'bathroom': '衛浴用品',
        'decor': '家居裝飾',
        'product1': '不鏽鋼廚具套裝',
        'product1-desc': '高品質不鏽鋼材質，耐用實用',
        'product2': '浴室收納套裝',
        'product2-desc': '防水防潮，實用美觀',
        'product3': '現代風格裝飾品',
        'product3-desc': '簡約時尚，提升家居品味',
        'product4': '陶瓷餐具套裝',
        'product4-desc': '精美陶瓷，安全環保',
        'product5': '浴室清潔套裝',
        'product5-desc': '專業清潔，方便實用',
        'product6': '創意擺件',
        'product6-desc': '獨特設計，彰顯個性',
        'inquiry': '詢價',
        'contact-title': '聯繫我們',
        'contact-info': '聯繫信息',
        'send-message': '發送消息',
        'name': '姓名',
        'subject': '主題',
        'message': '消息',
        'send': '發送',
        'years': '年行業經驗',
        'products-caterory': '種產品',
        'countries': '個國家',
        'latest-products': '最新產品',
        'view-more': '查看更多產品',
        'testimonials': '客戶評價',
        'ready-to-start': '準備好開始合作了嗎？',
        'contact-us-now': '立即聯繫我們，獲取專業的產品諮詢和報價',
        'contact-subtitle': '我們期待與您建立長期合作關係',
        'address-title': '公司地址',
        'tel-title': '聯繫電話',
        'email-title': '電子郵箱',
        'hours-title': '工作時間',
        'hours': '週一至週五: 9:00 - 18:00',
        'products-subtitle': '精選優質家居用品，滿足您的各種需求',
        'more-products': '更多產品',
        'contact-for-more': '請聯繫我們獲取完整產品目錄',
        'testimonial1': '"EVER SOURCE 提供的產品質量非常好，價格也很合理。他們的服務非常專業，交貨準時，是我們值得信賴的合作夥伴。"',
        'testimonial1-role': '美國零售商',
        'testimonial2': '"與 EVER SOURCE 合作多年，他們總能提供優質的產品和專業的服務。他們的團隊反應迅速，解決問題及時，是我們重要的供應商。"',
        'testimonial2-role': '西班牙分銷商',
        'testimonial3': '"EVER SOURCE 的產品種類豐富，質量穩定，價格有競爭力。他們的物流服務也很可靠，是我們長期合作的夥伴。"',
        'testimonial3-role': '澳大利亞進口商'
    },
    'en': {
        'home': 'Home',
        'about': 'About Us',
        'products': 'Products',
        'contact': 'Contact',
        'slogan': 'Professional Home Goods Cross-border B2B Wholesale Trade',
        'slogan-desc': 'Providing Cost-effective One-stop Procurement Solutions for Global Retailers',
        'contact-us': 'Contact Us',
        'feature1': 'Global Supply Chain',
        'feature1-desc': 'Deep integration of Chinese quality manufacturing resources and global market demand',
        'feature2': 'Rich Products',
        'feature2-desc': 'Providing diverse home goods options',
        'feature3': 'Professional Service',
        'feature3-desc': 'Providing professional one-stop service for overseas retailers',
        'address': 'Address: FLAT/RM 122 1/F LIVEN HOUSE 61-63 KING YIP STREET KWUN TONG',
        'tel': 'Tel: 852 6209 7685',
        'email': 'Email: eversource739@gmail.com',
        'email-input':'Email',
        'about-title': 'About Us',
        'about-desc': 'We are a company specializing in cross-border B2B wholesale trade of home goods, committed to providing cost-effective one-stop procurement solutions for overseas retailers, distributors, and chain supermarkets. Through deep integration of Chinese quality manufacturing resources and global market demand, we have established an efficient and stable international supply chain system.',
        'about-subtitle':'Professional Home Goods Supplier, Providing High-quality Products',
        'mission': 'Our Mission',
        'mission-desc': 'To provide high-quality, innovative, and eco-friendly home goods to global customers, promoting Chinese manufacturing to the world.',
        'vision': 'Our Vision',
        'vision-desc': 'To become a leading global B2B trading platform for home goods, building a trustworthy international brand.',
        'values': 'Core Values',
        'value1': 'Integrity in Business, Customer First',
        'value2': 'Quality First, Innovation Driven',
        'value3': 'Win-win Cooperation, Sustainable Development',
        'value4': 'Environmental Responsibility, Green Future',
        'team-title': 'Professional Team',
        'team1': 'Procurement Team',
        'team1-desc': 'Professional procurement team ensuring product quality and price advantages',
        'team2': 'International Business',
        'team2-desc': 'Experienced international business team providing professional services',
        'team3': 'Logistics Team',
        'team3-desc': 'Efficient logistics team ensuring timely delivery',
        'products-title': 'Products',
        'all': 'All',
        'kitchen': 'Kitchenware',
        'bathroom': 'Bathroom',
        'decor': 'Home Decor',
        'product1': 'Stainless Steel Kitchen Set',
        'product1-desc': 'High-quality stainless steel, durable and practical',
        'product2': 'Bathroom Storage Set',
        'product2-desc': 'Waterproof and moisture-proof, practical and beautiful',
        'product3': 'Modern Style Decorations',
        'product3-desc': 'Simple and stylish, enhance home taste',
        'product4': 'Ceramic Tableware Set',
        'product4-desc': 'Exquisite ceramic, safe and eco-friendly',
        'product5': 'Bathroom Cleaning Set',
        'product5-desc': 'Professional cleaning, convenient and practical',
        'product6': 'Creative Ornaments',
        'product6-desc': 'Unique design, show personality',
        'inquiry': 'Inquiry',
        'contact-title': 'Contact Us',
        'contact-info': 'Contact Information',
        'send-message': 'Send Message',
        'name': 'Name',
        'subject': 'Subject',
        'message': 'Message',
        'send': 'Send',
        'years': 'Years of Experience',
        'products-caterory': 'Products',
        'countries': 'Countries',
        'latest-products': 'Latest Products',
        'view-more': 'View More Products',
        'testimonials': 'Testimonials',
        'ready-to-start': 'Ready to Start?',
        'contact-us-now': 'Contact us now for professional product consultation and quotes',
        'contact-subtitle': 'We look forward to establishing a long-term partnership with you',
        'address-title': 'Company Address',
        'tel-title': 'Contact Number',
        'email-title': 'Email',
        'hours-title': 'Business Hours',
        'hours': 'Monday to Friday: 9:00 - 18:00',
        'products-subtitle': 'Premium Home Goods to Meet Your Every Need',
        'more-products': 'More Products',
        'contact-for-more': 'Contact us for the complete product catalog',
        'testimonial1': '"EVER SOURCE provides excellent quality products at reasonable prices. Their service is very professional, and they deliver on time. They are a trustworthy partner."',
        'testimonial1-role': 'US Retailer',
        'testimonial2': '"We have been working with EVER SOURCE for many years. They always provide high-quality products and professional service. Their team responds quickly and solves problems promptly. They are an important supplier for us."',
        'testimonial2-role': 'Spanish Distributor',
        'testimonial3': '"EVER SOURCE offers a wide variety of products with stable quality and competitive prices. Their logistics service is also reliable. They are our long-term partner."',
        'testimonial3-role': 'Australian Importer'
    }
};

function updateLanguage(lang) {
    document.documentElement.lang = lang;
    const elements = document.querySelectorAll('[data-lang]');
    elements.forEach(element => {
        const key = element.getAttribute('data-lang');
        if (translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
}

function updateActiveNav() {
    const currentPath = window.location.pathname;
    const navLinks = document.querySelectorAll('nav ul li a');
    
    navLinks.forEach(link => {
        link.classList.remove('active');
        if (link.getAttribute('href') === currentPath.split('/').pop()) {
            link.classList.add('active');
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const languageSelect = document.getElementById('language-select');
    const savedLanguage = localStorage.getItem('language') || 'zh-TW';
    
    languageSelect.value = savedLanguage;
    updateLanguage(savedLanguage);
    updateActiveNav();

    languageSelect.addEventListener('change', (e) => {
        const selectedLanguage = e.target.value;
        localStorage.setItem('language', selectedLanguage);
        updateLanguage(selectedLanguage);
    });
}); 